### PR TITLE
Feature/publish for first time

### PR DESCRIPTION
**Pull request by uglow**

### CODE REVIEW

**Comment by uglow** [comment]
Created by mistake

**Comment by alexcasalboni** [comment]
Hi @uglow 👋  happy to collaborate on this with you, if you've added new features or fixed bugs 😄

**Comment by uglow** [comment]
Hi @alexcasalboni , yes, I/we (my company) would be happy to collaborate too. 

Basically I’ve updated the build tooling to ESBuild and added support for sharing comparison graphs. 

Additionally, I’ve created an NPM package for that NodeJS script that is an alternative to execute.sh, but provides support for include-directives in the payload (so you can reference external JSON or JS files).

**Comment by alexcasalboni** [comment]
Sounds great 🚀 

How time-consuming would it be for you to open a PR for each change? (e.g. one for ESBuild, one for comparison graphs sharing, etc.)

If that doesn't work, at least I'd try to separate the comparison graph sharing feature into its own PR.

Once merged here, I'll make sure the changes are deployed to https://lambda-power-tuning.show for everyone (It's an Amplify Hosting app), so you don't need to roll out your own custom UI. Hopefully, this is a win-win 🎉

**Comment by uglow** [comment]
I can open a PR for the UI changes. I think the Node package should be in it's own repo - which I'll continue to support - as it is not tied to the UI at all. I'll prepare a PR in the next few days. 👍

**Comment by alexcasalboni** [comment]
Thank you 🙏  Yes, I'd also prioritize the new feature / UI changes 🚀

**Pull request closed without merging**
